server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        # Rota de Login (LIVRE)
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**

        # Rota de Pagamentos (PROTEGIDA)
        - id: payment-service
          uri: http://localhost:8081
          predicates:
            - Path=/payments/**
          filters:
            - name: JwtAuthFilter
