server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/payments/**
          filters:
            - name: JwtAuthFilter

        # Rota para expor os docs do Payment Service atrav√©s do Gateway
        - id: payment-docs
          uri: http://localhost:8082
          predicates:
            - Path=/payment-docs/**
          filters:
            - RewritePath=/payment-docs/(?<path>.*), /\${path}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Payment Service
        url: /payment-docs/v3/api-docs
      - name: Gateway Service
        url: /v3/api-docs

jwt:
  secret: ${JWT_SECRET:minha_chave_secreta_muito_longa_com_mais_de_32_caracteres}

management:
  tracing:
    sampling:
      probability: 1.0
