server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        # Rota de Login: Repassa o JSON diretamente para o Auth-Service
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**

        # Rota de Pagamentos: Exige o Token via Filtro
        - id: payment-service
          uri: http://localhost:8081
          predicates:
            - Path=/payments/**
          filters:
            - name: JwtAuthFilter
