server:
  port: 8083

spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    virtual-host: ${RABBITMQ_VHOST}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000ms
          max-attempts: 3
          multiplier: 2.0
        default-requeue-rejected: false

logging:
  file:
    name: ../logs/notification-service.log
