server:
  port: 8083

spring:
  application:
    name: notification-service
  rabbitmq:
    host: jaragua.lmq.cloudamqp.com
    port: 5672
    username: eglojydb
    password: YJAne6ylmzLLswXLoQfVeFFTwYlAUY2G
    virtual-host: eglojydb

logging:
  file:
    name: ../logs/notification-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] [%thread] %-5level %logger{36} - %msg%n"
